## makeCacheMatrix
##
## Factory to create an CacheMatrix object that contains a matrix its inverse
## matrix.
##
## This object doesn't automatically calculate the inverse matrix, see the
## function cacheSolve below.
##
## CacheMatrix (object)
##
## get_matrix: Get the original matrix
## set_matrix: Set the original matrix
## get_inverse: Get the inverse matrix
## set_inverse: Set the inverse matrix
##
## ---
##
## cacheSolve
##
## Calculate the inverse matrix using an object generated by makeMatrix.
##
## This function modifies the state of the object that will store the inverse
## matrix.


## Create a new CacheMatrix object.
##
## x: matrix object
## return: CacheMatrix object
makeCacheMatrix <- function(x = matrix()) {

  m <- x
  i <- NULL

  set_matrix <- function(x) {
    m <<- x
    i <<- NULL
  }

  get_matrix <- function() {
    m
  }

  set_inverse <- function(inverse) {
    i <<- inverse
  }

  get_inverse <- function() {
    i
  }

  result <- list(
    set_matrix = set_matrix,
    get_matrix = get_matrix,
    set_inverse = set_inverse,
    get_inverse = get_inverse)

  return(result)
}


## Calculates the inverse for a CacheMatrix object. If it hasn't been calculated
## yet.
##
## x: CacheMatrix object
## ...: any extra param for inverse function (see ?solve)
## return: Inverse matrix
cacheSolve <- function(x, ...) {

  i <- x$get_inverse()
  
  if(!is.null(i)) {
    message("getting cached data")
    return(i)
  }

  m <- x$get_matrix()
  i <- solve(m, ...)

  x$set_inverse(i)

  return(i)
}
